---
# tasks file for worker

- name: Add repository for kubeadm
  yum_repository:
    name: Kubernetes
    description: YUM repo for kubeadm 
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: no

- name: Add repository for docker
  yum_repository:
    name: docker-repo
    description: repo for docker
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    enabled: yes
    gpgcheck: no

- name: Installing the docker software for k8s Cluster
  command: yum install docker-ce --nobest -y 

- name: Installing the Prerequisite software for k8s Cluster
  package:
          name: "{{ item }}"      
          state: present
  loop:
          - iproute-tc
          - kubeadm   

- name: Starting the Docker & Kubelet Services
  service:
         name:  "{{ item }}"
         state: started
         enabled: yes
  loop:
          - docker
          - kubelet  

- name: Changing the Docker Cgroup Driver
  copy: 
       dest: /etc/docker/daemon.json
       content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            } 
- name: Restarting the Docker Service
  service:
          name: docker 
          state: restarted


- name: Stopping firewall
  command: systemctl stop firewalld

- name: Updating the iptables
  copy:
        dest: /etc/sysctl.d/k8s.conif
        content: |
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1


- name: Loading the iptables
  shell: "sysctl --system"
          
- name: Change the value to ipv4 tables
  shell: "echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf"

- name: Enable the ipv4 tables
  shell: "sudo sysctl -p /etc/sysctl.conf"
  

- name: Joining the master node
  shell: "{{ master_token }}"
